services:
  # redis:
  #   image: redis:7
  #   container_name: dev_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--appendonly", "yes"]
  #   volumes:
  #     - redis_data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: dev_redis_commander
    restart: always
    ports:
      - "8083:8081"
    environment:
      REDIS_HOSTS: local:dev_redis:6379
      HTTP_USER: root
      HTTP_PASSWORD: admin
    # depends_on:
    #   - redis

volumes:
  redis_data:
    driver: local
